### PR TITLE
updated read device to cloud messages to the latest version of eventhubs sdk

### PR DESCRIPTION
**Pull request by amarzavery**
## Purpose

* Migrate to the latest version of azure-event-hubs sdk that is based on rhea.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [https://github.com/amarzavery/azure-iot-samples-node]
cd [azure-iot-samples-node]
git checkout [updateEH]
cd Quickstarts/read-d2c-messages
npm install
```

* Test the code

```
provide the iothub connectionstring in the sample and run the sample
node ReadDeviceToCloudMessages.js
```

## What to Check
Verify that the following are valid
* The sample runs in the same way as it used to run before. You should be able to receive messages from the eventhub associated  with the iothub.

### CODE REVIEW

**Comment by amarzavery** [comment]
@yzhong94 @dominicbetts @pierreca - Please review the PR and merge this. It fixes https://github.com/Azure-Samples/azure-iot-samples-node/issues/4

**Comment by dominicbetts** [comment]
@amarzavery - all looks good to me. But, please hold on before you merge. We have another PR to merge today that updates the folder structure (https://github.com/Azure-Samples/azure-iot-samples-node/pull/5). This PR is synchronized with some matching changes in the docs.

**Comment by yzhong94** [comment]
@dominicbetts I'm seeing merge conflict for this PR

**Comment by dominicbetts** [comment]
@yzhong94, @amarzavery 
Hi Yi, it looks like Amar created this PR after I added the new iot-hub folder, so Amar needs to fix the merge conflict in his fork. Thanks!

**Comment by amarzavery** [comment]
@yzhong94 - I will rebase the PR.

**Comment by amarzavery** [comment]
@yzhong94 @dominicbetts - The PR can now be merged. I have pulled in the new changes.

**Pull request merged**
